# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22438f7733c5e4721d96eb3c690707b2114bd3d89c9bac85fa3e1fb17cd2d95b4319f6654f00e13fb498ed0de1622f9b0dc6157a92cff4e89a52753cdc81e637

test:
  secret_key_base: 0efdb442ec170751e13d7cf77be571b86dafd81b6bafa760e45429607437d3e02bfb5c22695afd377d50b8bfcbf543facc481c9f7a5a9e6ad78189b062f250ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
